"""One declaration of the closed-model configuration, and the same schemas.

Six modules declared their own `ConfigDict(extra="forbid", frozen=True)` base
beside `typed_output.StrictOutputModel`, all with the same meaning: a shape
whose fields are exactly the declared ones and which cannot be mutated after
it is built. Six declarations is six places for one of them to drift.

`typed_output` owns that configuration now, and every base derives from it.
The schemas are the reason this is a test rather than a refactor note: a
provider call is made against `strict_output_schema`, and render profiles and
token layers seal identities over their own field values, so a base swap that
moved one generated byte would be a different measurement. The digests below
were recorded from the definitions as they stood before the bases changed.
"""

from __future__ import annotations

import ast
import hashlib
import importlib
import json
from pathlib import Path

import pytest

from corridor import typed_output
from source_scan_support import python_files, read_python, source_scan_cache  # noqa: F401

SOURCE_ROOT = Path(__file__).parents[1] / "src" / "corridor"

# sha256 of json.dumps(model_json_schema(), sort_keys=True), recorded before
# the shared base was introduced. A provider schema or a sealed identity that
# changes shape has to be a deliberate, separately measured change.
SEALED_SCHEMAS = {
    "corridor.pdf_evaluation.GoldSet": "47f68c02ccb9a3345d212d92cd801e85168dbfc30bb81b4fb469ab80f39f4a6a",
    "corridor.pdf_evaluation.EngineRun": "76c0fc642cec8697f5f6a46dcdeccfd8b6ffa2b05058a1f49528f18f75aa3495",
    "corridor.pdf_evaluation.EvaluationReport": "63d74f2c3a3f71777f0b8ec352b9397ef1fae3e38c8d1e1439980dd410b8fdcb",
    "corridor.page_inventory_evaluation.RoutingGoldSet": "bf48c33631dbcfa621d4606b4120eadcd52bdcace7cd07637d60e8781e680a4a",
    "corridor.page_inventory_evaluation.RoutingRun": "8ba3567a00189db3e0cc6a48e53991f6de55be438a54852d9332db566966afb7",
    "corridor.page_inventory_evaluation.Stage1Evaluation": "fd98a1bb4aaee82278d75c5a1c4d970064cee3e3a9a9d35042f172447b9cffe4",
    "corridor.pipeline_contracts.PipelineScope": "88965f01ca127cc6435ca8790134d1f7160cbc921d50aa6401c096f85d57fcd0",
    "corridor.pipeline_contracts.QualificationPolicy": "80ceb974d2680470a453e89b6c49a12d4490a3bad9ba2c2cdd409d27fa1c831b",
    "corridor.pipeline_contracts.MaintainerAcceptance": "49a78e9c632e17f739e60223f445a7fcee1bc11746e49b56d764fffc01b6e533",
    "corridor.render_profiles.RenderProfile": "e1cbf341624f2ea1f510935a1d029c8af4bca5efc6dca5c7d4f4de69963d3c19",
    "corridor.render_profiles.PageBox": "8d4703c7054f22e1ab5af7e3168d5ad45174712c926218de6bbc559557546951",
    "corridor.token_layers.Token": "c69b897e9ac2c098996a81b9a69276f3311e7f6164b200a517a9b65040f47e15",
    "corridor.email_spine.EmailThreadOutput": "d0247987d8d054ad61250447cb512861f13b94a649d5fa3cdcacc3d81d226716",
    "corridor.minutes_spine.MinutesOutput": "6c297318ddc4025534847d282907734ca7bda881b3f170917c1dc3aa03ce144a",
    "corridor.prose_interpretation.ProseInterpretationOutput": "80973da26c64f8700113dc88338dea0870abbf0c882772705df2d42c264b008d",
    # Recorded from the reader Page Inventory's own base before it joined the
    # shared one. The inventory is a measurement input: a routing decision is
    # compared against a recorded gold set, so a moved schema byte would be a
    # different reading rather than the same one under a shared declaration.
    "corridor.page_inventory.PdfRect": "47ec5ee53350cffff4daecfa9981bd0c42cb2d6d47415757f3b6b1ed45738b8b",
    "corridor.page_inventory.PageBoxes": "0e1a04a936721e92e4be327c0b6c907abe802322dd25c5fe859f52401a54ed62",
    "corridor.page_inventory.InventoryRegion": "2e10c88031962dfb8c41aae12a2e34abb109322f9478b437d0c8a9e9c1a454f4",
    "corridor.page_inventory.TableRegionEvidence": "b67e65f49cb04fd6f66a75ad32c480bc65bdd74b48e59689e57793329317c0d5",
    "corridor.page_inventory.PageInventory": "f7783952a37bcba438f04e018c402deb404249ec7837063f46d8098fcc04be6e",
    "corridor.page_inventory.RoutingRegion": "9095ea9ef165e2d0ff39c7243a48e493981f71b199b636abe46278c5d51129bb",
    "corridor.page_inventory.StructuralTrigger": "ac4d818f6ce33e75e1ff55d9e7c9dd5c028564347c00e93058348ac70ecb3cbc",
    "corridor.page_inventory.PageRoutingDecision": "fb89e0a06c392a6c1f95fb500e87518b6a1b8926ecd47078b83156f47b388f5e",
}

# No module declares the closed-model configuration for itself any more. The
# list may fall and may never rise: a new own base joins it only with the seam
# that removes it.
OWN_BASE_ALLOWLIST: dict[str, str] = {}


def _schema_digest(dotted: str) -> str:
    module, name = dotted.rsplit(".", 1)
    model = getattr(importlib.import_module(module), name)
    return hashlib.sha256(
        json.dumps(model.model_json_schema(), sort_keys=True).encode()
    ).hexdigest()


@pytest.mark.parametrize("dotted", sorted(SEALED_SCHEMAS))
def test_the_generated_schema_did_not_move_when_the_bases_did(dotted):
    assert _schema_digest(dotted) == SEALED_SCHEMAS[dotted]


def test_the_strict_provider_base_is_the_shared_base_plus_strictness():
    """`strict=True` is the provider boundary's own rule, not every shape's."""
    assert issubclass(typed_output.StrictOutputModel, typed_output.ClosedModel)
    assert typed_output.ClosedModel.model_config == {"extra": "forbid", "frozen": True}
    assert typed_output.StrictOutputModel.model_config == {
        "extra": "forbid", "frozen": True, "strict": True,
    }
    assert typed_output.ClosedModel.model_config.get("strict") is None


def _declared_closed_bases() -> dict[str, list[str]]:
    """Every class whose own body sets extra="forbid", per module."""
    declared: dict[str, list[str]] = {}
    for path in python_files(SOURCE_ROOT):
        if path.name == "__init__.py" or "migrations" in path.parts:
            continue
        module = ".".join(path.relative_to(SOURCE_ROOT).with_suffix("").parts)
        for node in ast.walk(read_python(path).tree):
            if not isinstance(node, ast.ClassDef):
                continue
            for statement in node.body:
                if (isinstance(statement, ast.Assign)
                        and any(getattr(target, "id", None) == "model_config" for target in statement.targets)
                        and "extra" in ast.dump(statement.value)
                        and "forbid" in ast.dump(statement.value)):
                    declared.setdefault(module, []).append(node.name)
    return declared


def test_only_typed_output_declares_the_closed_model_configuration():
    """A module that repeats the ConfigDict owns a second copy of the rule."""
    declared = _declared_closed_bases()

    assert declared.pop("typed_output") == ["ClosedModel"], (
        "StrictOutputModel adds strictness to the shared declaration rather than repeating it"
    )
    assert sorted(declared) == sorted(OWN_BASE_ALLOWLIST), (
        "a module declaring its own closed-model config joins the allowlist with "
        "the seam that removes it, or derives from typed_output.ClosedModel"
    )
    for module, reason in OWN_BASE_ALLOWLIST.items():
        assert len(reason.split()) >= 8, f"{module} says which seam removes it"


@pytest.mark.parametrize(
    "dotted",
    [
        "corridor.pdf_evaluation.ContractModel",
        "corridor.page_inventory_evaluation.Stage1Model",
        "corridor.pipeline_contracts.PipelineContract",
        "corridor.render_profiles.RenderModel",
        "corridor.token_layers.TokenModel",
        "corridor.page_inventory.InventoryModel",
    ],
)
def test_every_measurement_base_is_the_shared_base_under_its_own_name(dotted):
    """The names stay, so importers do not move; the configuration is one."""
    module, name = dotted.rsplit(".", 1)
    base = getattr(importlib.import_module(module), name)

    assert issubclass(base, typed_output.ClosedModel)
    assert base.model_config == typed_output.ClosedModel.model_config
