"""Read the built workflow's immutable receipts for #532, without another store.

Presentation remains an explicit #558 event: a database snapshot cannot tell
whether a person saw or opened a packet. Domain acts instead use the exact
records they already append, including unfinished/deferred work and preparation
attempts. No model, migration, analytics role or decision authority is added.

Where a receipt predates deployment-context recording, the report preserves
that limit and binds its declared observation period separately. It never
rewrites history with the exporter process's current revision or wall clock.
Only identities, digests, counts and recorded instants leave this reader;
source text, annotations, email addresses and generated bytes do not.
"""

from __future__ import annotations

from dataclasses import replace
from datetime import datetime
import json
from typing import Any, Callable, Iterable

from sqlalchemy import select
from sqlalchemy.orm import Session

from corridor.analytics import (
    AnalyticsEvent, EventFamily, act_outcome, child_decision_action, declared_payload, default_binding,
)
from corridor import models as m
from corridor.pilot_measurement import MeasurementPeriod
from corridor.measurement_collection import binding_for_session


def observed_database_identity(session: Session) -> str:
    """The immutable #656 attestation on the actual DB; no monitor privilege."""
    binding = binding_for_session(session)
    if not binding.database_identity:
        raise ValueError("customer database origin is unavailable; attest through the existing customer router before export")
    return binding.database_identity


def read_domain_receipts(
    session: Session, periods: Iterable[MeasurementPeriod], *, events: Iterable[AnalyticsEvent] = (),
) -> tuple[AnalyticsEvent, ...]:
    """Read project-scoped, append-only evidence through each declared close.

    The caller uses the customer's existing database read boundary. Disposition
    and release authorization are read as receipts, never inferred from a UI
    response or from a log message that may have preceded a rolled-back commit.
    """

    periods = tuple(periods)
    observed_events = tuple(events)
    output: list[AnalyticsEvent] = []
    with session.no_autoflush:
        bound_origin = binding_for_session(session)
        origin = observed_database_identity(session)
        if any(p.database_identity != origin for p in periods):
            raise ValueError("measurement period does not name the connected database origin")
        if len({(p.customer_id, p.environment) for p in periods}) != 1:
            raise ValueError("one customer database export cannot blend customer/environment origins")
        customer_id, environment = next(iter({(p.customer_id, p.environment) for p in periods}))
        if (customer_id, environment) != (bound_origin.customer_id, bound_origin.environment):
            raise ValueError("period customer/environment differs from the database attestation")
        for project_id in sorted({p.project_id for p in periods}):
            if session.get(m.Project, project_id) is None:
                raise ValueError("measurement period names no project in this customer database")
            project_periods = sorted((p for p in periods if p.project_id == project_id), key=lambda p: p.start)
            through = max(p.end for p in project_periods)

            def rows(model, at=None):
                query = select(model).where(model.project_id == project_id)
                if at is not None:
                    query = query.where(at < through)
                return session.scalars(query.order_by(model.id)).all()

            def emit(family, row, at: datetime, **payload):
                if at >= through:
                    return
                period = next((p for p in project_periods if p.start <= at < p.end), None)
                binding = period.binding if period else default_binding()
                matches = [e for e in observed_events if e.family == family
                           and e.payload.get("project_id") == project_id
                           and e.binding.database_identity == origin
                           and e.binding.customer_id == customer_id
                           and same_act(e, payload, row, at)]
                if family == EventFamily.SOURCE_CAPTURE:
                    outcomes = {act_outcome(e) for e in matches}
                    if len(outcomes) > 1:
                        raise ValueError("conflicting capture outcomes for one document registration")
                    payload["outcome"] = next(iter(outcomes)) if outcomes else "unavailable"
                    payload["attempt_outcomes"] = sorted({
                        declared_payload(e)["outcome"] for e in observed_events
                        if e.family == family and e.payload.get("document_id") == row.id
                        and e.payload.get("project_id") == project_id
                        and e.binding.database_identity == origin and e.binding.customer_id == customer_id
                        and at <= e.occurred_at < through and declared_payload(e).get("outcome")
                    })
                if matches and len({json.dumps(e.binding.as_dict(), sort_keys=True) for e in matches}) == 1:
                    binding = matches[0].binding
                    payload["binding_event_ids"] = [e.event_id for e in matches]
                else:
                    # A declared cohort is not proof of what an older receipt
                    # recorded. Keep unsupported context unavailable instead
                    # of stamping the exporter deployment onto history.
                    unavailable = ["code_revision", "product_revision", "packetizer_rules_version",
                                   "source_configuration", "connector_configuration", "template_identity",
                                   "mapping_identity", "enabled_feature_flags"]
                    for known, field in (("code_revision", "code_revision"), ("product_revision", "product_revision"),
                                         ("grouping_rule_version", "packetizer_rules_version"),
                                         ("output_template", "template_identity"), ("field_mapping", "mapping_identity"),
                                         ("enabled_feature_flags", "enabled_feature_flags")):
                        if payload.get(known) is not None:
                            unavailable.remove(field)
                    payload["unavailable_binding_fields"] = unavailable
                binding = replace(binding, customer_id=customer_id, environment=environment,
                                  database_identity=origin)
                profile = profiles.get(payload.get("issue_profile_id"))
                if profile:
                    payload.update(issue_profile_identity=profile.profile_identity,
                                   issue_profile_version=profile.profile_version,
                                   issue_profile_sha256=profile.content_sha256)
                elif period:
                    payload.setdefault("issue_profile_identity", period.issue_profile_identity)
                    payload.setdefault("issue_profile_version", period.issue_profile_version)
                    payload.setdefault("issue_profile_sha256", period.issue_profile_sha256)
                if payload.get("code_revision"):
                    binding = replace(binding, code_revision=payload["code_revision"],
                                      product_revision=payload["product_revision"])
                for name, attribute in (("output_template", "template_identity"), ("field_mapping", "mapping_identity")):
                    if value := payload.get(name):
                        updates: dict[str, Any] = {attribute: f"{value['identity']}:{value['version']}"}
                        binding = replace(binding, **updates)
                if payload.get("enabled_feature_flags") is not None:
                    binding = replace(binding, enabled_feature_flags=tuple(payload["enabled_feature_flags"]))
                if payload.get("grouping_rule_version"):
                    binding = replace(binding, packetizer_rules_version=payload["grouping_rule_version"])
                output.append(AnalyticsEvent(
                    family=family, occurred_at=at, binding=binding,
                    event_id=f"receipt:{row.__tablename__}:{row.id}:{family.value}",
                    payload={"project_id": project_id, "receipt_id": row.id,
                             "receipt": {"table": row.__tablename__, "id": row.id},
                             "cohort_period_id": period.period_id if period else None,
                             "cohort_binding_origin": "declared measurement period; retained fields take precedence",
                             "customer_binding_verified": customer_verified,
                             **payload},
                ))

            profiles = {r.id: r for r in rows(m.IssueProfile)}
            documents = {r.id: r for r in rows(m.Document, m.Document.created_at)}
            deliveries = {r.id: r for r in rows(m.SourceDelivery, m.SourceDelivery.received_at)}
            if any(r.customer != customer_id for r in deliveries.values()):
                raise ValueError("retained delivery customer does not match the declared database origin")
            customer_verified = True
            document_by_delivery = {r.source_delivery_id: r for r in documents.values() if r.source_delivery_id}
            for row in deliveries.values():
                document = document_by_delivery.get(row.id)
                emit(EventFamily.SOURCE_ARRIVAL, row, row.received_at,
                     source_identity=f"delivery:{row.id}", source_class=document.doc_type if document else
                     row.metadata_json.get("source_class", "unavailable"),
                     content_sha256=row.content_sha256,
                     customer_id=row.customer, disposition=row.disposition, refusal_reason=row.refusal_reason,
                     source_configuration={"identity": row.configuration_identity, "version": row.configuration_version},
                     connector_configuration={"transport": row.transport, "channel": row.channel},
                     timestamp_basis="SourceDelivery.received_at; arrival at Corridor intake")
            for row in documents.values():
                emit(EventFamily.SOURCE_CAPTURE, row, row.created_at,
                     source_identity=f"delivery:{row.source_delivery_id}" if row.source_delivery_id else f"document:{row.id}",
                     document_id=row.id, content_sha256=row.sha256, source_class=row.doc_type,
                     timestamp_basis="Document.created_at; durable registered document, not inferred upload start")
            groups = {r.id: r for r in rows(m.DeltaGroup)}
            for row in rows(m.ProposedDelta, m.ProposedDelta.created_at):
                group = groups[row.group_id]
                document = documents.get(group.document_id)
                source = (f"delivery:{document.source_delivery_id}" if document and document.source_delivery_id else
                          f"document:{document.id}" if document else None)
                emit(EventFamily.PROPOSED_DELTA_CREATION, row, row.created_at,
                     delta_id=row.id, source_identity=source,
                     source_class=document.doc_type if document else "unavailable", source_family=row.source_family,
                     target_field=row.target_field, source_revision=row.source_revision,
                     comparison_rule_version=row.comparison_rule_version,
                     content_sha256=row.content_sha256, timestamp_basis="ProposedDelta.created_at")
            decisions = {r.disposition_id: r for r in rows(m.DeltaRecordDecision)}
            for row in rows(m.DeltaDisposition, m.DeltaDisposition.decided_at):
                decision = decisions.get(row.id)
                emit(EventFamily.CHILD_DECISION, row, row.decided_at, delta_id=row.delta_id,
                     action=row.disposition, outcome="resolved",
                     principal_subject=row.decided_by_principal, policy=row.decided_by_policy,
                     revision_id=decision.revision_id if decision else None)
            for row in rows(m.DeltaDeferral, m.DeltaDeferral.deferred_at):
                emit(EventFamily.CHILD_DECISION, row, row.deferred_at, delta_id=row.delta_id,
                     action="defer", outcome="deferred", principal_subject=row.scheduled_by_principal,
                     deferred_until=row.deferred_until.isoformat() if row.deferred_until else None,
                     wake_condition=row.wake_condition)
            for row in rows(m.DeltaSupersession, m.DeltaSupersession.superseded_at):
                emit(EventFamily.DELTA_SUPERSESSION, row, row.superseded_at,
                     prior_delta_id=row.prior_delta_id, superseding_delta_id=row.superseding_delta_id,
                     source_reading_id=row.source_reading_id, minutes_capture_id=row.minutes_capture_id)
            packet_children = rows(m.DeltaReviewPacketChild)
            for row in rows(m.DeltaReviewPacketReceipt, m.DeltaReviewPacketReceipt.decided_at):
                members = [c for c in packet_children if c.receipt_id == row.id]
                emit(EventFamily.PACKET_SAVE, row, row.decided_at, outcome="saved",
                     grouping_rule_version=row.grouping_rule_version, grouping_key_kind=row.grouping_key_kind,
                     grouping_key=row.grouping_key, revision_id=row.revision_id,
                     principal_subject=row.decided_by_principal,
                     children=[{"delta_id": c.delta_id, "outcome": c.outcome,
                                "decision_id": c.decision_id, "follow_up_plan_id": c.follow_up_plan_id,
                                "deferral_id": c.deferral_id} for c in members])
                for child in members:
                    if child.outcome == "needs_coordination":
                        emit(EventFamily.CHILD_DECISION, child, row.decided_at, outcome="saved",
                             delta_id=child.delta_id, action=child.outcome, revision_id=row.revision_id,
                             principal_subject=row.decided_by_principal)
            for row in rows(m.DeltaFollowUpPlan, m.DeltaFollowUpPlan.recorded_at):
                emit(EventFamily.FOLLOW_UP_PLAN_CREATION, row, row.recorded_at,
                     delta_id=row.delta_id, follow_up_plan_id=row.id, revision_id=row.revision_id,
                     principal_subject=row.recorded_by_principal)
            declarations = {r.id: r for r in rows(m.IssueCoverageDeclaration, m.IssueCoverageDeclaration.confirmed_at)}
            for row in declarations.values():
                content = json.loads(row.declaration)
                emit(EventFamily.COVERAGE_CONFIRMATION, row, row.confirmed_at,
                     coverage_declaration_id=row.id, issue_profile_id=row.issue_profile_id,
                     declaration_sha256=row.declaration_digest, reading_sha256=row.derived_reading_digest,
                     principal_subject=row.confirmed_by_principal, annotation_count=len(content.get("annotations", [])))
            requests = {r.id: r for r in rows(m.ReleasePreparationRequest, m.ReleasePreparationRequest.requested_at)}
            seen = set()
            for row in requests.values():
                declaration = declarations.get(row.coverage_declaration_id)
                reused = row.coverage_declaration_id in seen
                seen.add(row.coverage_declaration_id)
                emit(EventFamily.PREPARATION_REQUEST, row, row.requested_at, request_id=row.id,
                     issue_profile_id=row.issue_profile_id, coverage_declaration_id=row.coverage_declaration_id,
                     principal_subject=row.requested_by_principal, accepted_revision_id=row.accepted_revision_id,
                     annotation_count=len(json.loads(declaration.declaration).get("annotations", [])) if declaration else None,
                     reading_sha256=declaration.derived_reading_digest if declaration else None,
                     unchanged_declaration_reused=reused)
            for row in rows(m.ReleasePreparationAttempt, m.ReleasePreparationAttempt.finished_at):
                request = requests.get(row.request_id)
                emit(EventFamily.PREPARATION_ATTEMPT, row, row.finished_at,
                     request_id=row.request_id, attempt_id=row.id, started_at=row.started_at.isoformat(),
                     finished_at=row.finished_at.isoformat(), outcome=row.outcome, candidate_id=row.candidate_id,
                     refusal_code=row.refusal_code,
                     issue_profile_id=request.issue_profile_id if request else None,
                     coverage_declaration_id=request.coverage_declaration_id if request else None)
            for row in rows(m.ReleasePreparationReading, m.ReleasePreparationReading.bound_at):
                request = requests.get(row.request_id)
                emit(EventFamily.PREPARATION_ATTEMPT, row, row.bound_at,
                     request_id=row.request_id, started_at=row.bound_at.isoformat(), outcome="started",
                     timestamp_basis="ReleasePreparationReading.bound_at; retained start of input binding",
                     issue_profile_id=request.issue_profile_id if request else None,
                     coverage_declaration_id=request.coverage_declaration_id if request else None)
            candidate_artifacts = rows(m.ReleaseCandidateArtifact)
            for row in rows(m.ReleaseCandidate, m.ReleaseCandidate.prepared_at):
                content = json.loads(row.input_declaration)
                emit(EventFamily.RELEASE_CANDIDATE_PREPARATION, row, row.recorded_at,
                     candidate_id=row.id, candidate_identity=row.candidate_identity,
                     bound_prepared_at=row.prepared_at.isoformat(),
                     timestamp_basis="ReleaseCandidate.recorded_at; prepared_at freezes inputs before rendering",
                     accepted_revision_id=row.accepted_revision_id, readiness=row.readiness,
                     coverage_declaration_id=row.coverage_declaration_id, issue_profile_id=row.issue_profile_id,
                     code_revision=row.code_revision, product_revision=row.product_revision,
                     output_template=content.get("output_template"), field_mapping=content.get("field_mapping"),
                     enabled_feature_flags=content.get("enabled_feature_flags"),
                     configured_artifact_types=content["configured_artifact_types"],
                     artifacts=[{"artifact_type": "updated_ucm", "content_sha256": row.ucm_content_sha256}] +
                     [{"artifact_type": a.artifact_type, "content_sha256": a.content_sha256}
                      for a in candidate_artifacts if a.candidate_id == row.id])
            for row in rows(m.ReleasePackage, m.ReleasePackage.authorized_at):
                emit(EventFamily.RELEASE_AUTHORIZATION, row, row.authorized_at,
                     candidate_id=row.candidate_id, candidate_identity=row.candidate_identity,
                     accepted_revision_id=row.accepted_revision_id, package_identity=row.package_identity,
                     status="authorized", issue_profile_id=row.issue_profile_id,
                     principal_subject=row.authorized_by_principal, receipt_schema_version=row.receipt_schema_version)
            # Tokens alone are not a price. Keep each recorded model run visible
            # as unreconciled usage until an actual provider/billing receipt is
            # supplied. A deterministic native run has no model call to bill.
            if documents:
                runs = session.scalars(select(m.ExtractionRun).where(
                    m.ExtractionRun.document_id.in_(documents), m.ExtractionRun.completed_at < through
                ).order_by(m.ExtractionRun.id)).all()
                for row in runs:
                    if row.model is not None:
                        document = documents[row.document_id]
                        emit(EventFamily.PROVIDER_USAGE, row, row.completed_at,
                             extraction_run_id=row.id,
                             usage_id=f"extraction_run:{row.id}", mode="unclassified_usage",
                             purpose="unavailable", source_class=document.doc_type, model=row.model,
                             prompt_version=row.prompt_version, policy_version=row.postprocessor_sha256,
                             actual_cost_usd=None, usage=row.token_usage_json,
                             evidence_reference=f"extraction_runs:{row.id}",
                             unavailable_reason="run tokens do not establish billed cost, retries, purpose or cache origin")
    return tuple(output)


def same_act(event: AnalyticsEvent, receipt: dict[str, Any], row, at: datetime) -> bool:
    """Whether this logged event and this database receipt describe the same act.

    Each family declares its own corroboration in ``_SAME_ACT``; a family
    without one is never corroborated. Corroboration names one exact act,
    never a shared declaration, digest or delta alone. The event is read
    through its declared keys, so a row logged under a legacy spelling still
    corroborates.
    """
    corroborates = _SAME_ACT.get(event.family)
    if corroborates is None:
        return False
    p = declared_payload(event)
    expected_at = row.prepared_at if isinstance(row, m.ReleaseCandidate) else at
    if event.occurred_at != expected_at or (p.get("refusal_code") and event.family != EventFamily.PREPARATION_ATTEMPT):
        return False
    return corroborates(p, act_outcome(event), receipt, row)


def _same_preparation_request(p, outcome, receipt, row) -> bool:
    return (p.get("request_id") == row.id and outcome == "requested"
            and p.get("principal_subject") == row.requested_by_principal)


def _same_coverage_confirmation(p, outcome, receipt, row) -> bool:
    return (p.get("coverage_declaration_id") == row.id
            and p.get("unchanged_declaration_reused") is False
            and p.get("principal_subject") == row.confirmed_by_principal)


def _same_preparation_attempt(p, outcome, receipt, row) -> bool:
    if isinstance(row, m.ReleasePreparationReading):
        return (p.get("request_id") == row.request_id and outcome == "started"
                and p.get("started_at") == row.bound_at.isoformat())
    return (p.get("attempt_id") == row.id and p.get("request_id") == row.request_id
            and outcome == row.outcome and p.get("started_at") == row.started_at.isoformat())


def _same_packet_save(p, outcome, receipt, row) -> bool:
    return p.get("receipt_id") == row.id and outcome == "saved"


def _same_child_decision(p, outcome, receipt, row) -> bool:
    # The receipt speaks the record's disposition vocabulary; the event may
    # have been logged in the screen's, which child_decision_action translates.
    expected_action = receipt["action"]
    outcomes = {"deferred"} if expected_action == "defer" else {"saved", "resolved"}
    return (p.get("delta_id") == receipt["delta_id"]
            and child_decision_action(p.get("action")) == expected_action
            and outcome in outcomes)


def _same_delta_supersession(p, outcome, receipt, row) -> bool:
    return (p.get("prior_delta_id") == row.prior_delta_id
            and p.get("superseding_delta_id") == row.superseding_delta_id
            and p.get("source_reading_id") == row.source_reading_id
            and p.get("minutes_capture_id") == row.minutes_capture_id)


def _same_proposed_delta_creation(p, outcome, receipt, row) -> bool:
    return outcome in {None, "created"} and (p.get("delta_id") == row.id or row.id in p.get("delta_ids", []))


def _same_follow_up_plan_creation(p, outcome, receipt, row) -> bool:
    return p.get("follow_up_plan_id") == row.id and p.get("delta_id") == row.delta_id


def _same_release_candidate_preparation(p, outcome, receipt, row) -> bool:
    return p.get("candidate_identity") == row.candidate_identity and outcome == row.readiness


def _same_release_authorization(p, outcome, receipt, row) -> bool:
    return (p.get("package_identity") == row.package_identity and outcome == "authorized"
            and p.get("principal_subject") == row.authorized_by_principal)


def _same_source_arrival(p, outcome, receipt, row) -> bool:
    return (outcome == "recorded" and p.get("disposition") == row.disposition
            and (p.get("source_identity") == f"delivery:{row.id}" or p.get("source_delivery_id") == row.id))


def _same_source_capture(p, outcome, receipt, row) -> bool:
    return outcome in {"captured", "unavailable"} and p.get("document_id") == row.id


_SAME_ACT: dict[EventFamily, Callable[[dict[str, Any], str | None, dict[str, Any], Any], bool]] = {
    EventFamily.PREPARATION_REQUEST: _same_preparation_request,
    EventFamily.COVERAGE_CONFIRMATION: _same_coverage_confirmation,
    EventFamily.PREPARATION_ATTEMPT: _same_preparation_attempt,
    EventFamily.PACKET_SAVE: _same_packet_save,
    EventFamily.CHILD_DECISION: _same_child_decision,
    EventFamily.DELTA_SUPERSESSION: _same_delta_supersession,
    EventFamily.PROPOSED_DELTA_CREATION: _same_proposed_delta_creation,
    EventFamily.FOLLOW_UP_PLAN_CREATION: _same_follow_up_plan_creation,
    EventFamily.RELEASE_CANDIDATE_PREPARATION: _same_release_candidate_preparation,
    EventFamily.RELEASE_AUTHORIZATION: _same_release_authorization,
    EventFamily.SOURCE_ARRIVAL: _same_source_arrival,
    EventFamily.SOURCE_CAPTURE: _same_source_capture,
}
