"""Schema for the walking skeleton.

Three points differ from a naive reading of the spec and are easy to get
wrong, so they are called out here as well as in the ADRs:

- A Dependency has no mutable lifecycle status. Ready, Dismissal, Commitment
  Closure, Exceptions, and Coordination Plans supply the supported states
  (ADR-0002, ADR-0044).
- `Assertion` is a table, not a column. A ledger field value is an
  adjudicated conclusion; the assertions beneath it preserve what each
  source actually claimed (ADR-0001).
- `EvidenceLink.verified` means exactly one thing: the quote appears on
  the cited page. It says nothing about whether the claim is true.

Card 21 split this schema into one module per bounded context. Everything a
reader imported from ``corridor.models`` is still imported from
``corridor.models``: each family module declares an explicit ``__all__`` and
this package re-exports all of them, so ``from corridor.models import Fact``
means what it always meant. Importing every submodule here is load-bearing
rather than tidy -- ``Base.metadata`` is only complete once each family has been
imported, and Alembic autogenerate reads that metadata, so a family this file
forgot would silently disappear from the schema.
"""

from corridor.models.base import *  # noqa: F403
from corridor.models.project import *  # noqa: F403
from corridor.models.intake import *  # noqa: F403
from corridor.models.source import *  # noqa: F403
from corridor.models.spine import *  # noqa: F403
from corridor.models.delta import *  # noqa: F403
from corridor.models.extraction import *  # noqa: F403
from corridor.models.measurement import *  # noqa: F403
from corridor.models.admission import *  # noqa: F403
from corridor.models.publication import *  # noqa: F403
from corridor.models.assistance import *  # noqa: F403
from corridor.models.operations import *  # noqa: F403
from corridor.models.notifications import *  # noqa: F403
from corridor.models.schedule import *  # noqa: F403
from corridor.models.record import *  # noqa: F403
from corridor.models.coordination import *  # noqa: F403
from corridor.models.legacy import *  # noqa: F403
from corridor.models.history import *  # noqa: F403

__all__ = [  # noqa: F405
    "ANSWER_SEPARATOR",
    "ASSIGNMENT_DELIVERY_STATES",
    "ASSIGNMENT_NOTIFICATION_SUBJECT_KINDS",
    "ActiveExtractionRun",
    "ActiveRunDeclaration",
    "Assertion",
    "AssignmentNotification",
    "AssignmentNotificationAttempt",
    "AssignmentNotificationDispatch",
    "AssignmentNotificationFeedback",
    "AuditLog",
    "AutomaticCarryForwardOutcome",
    "AutomaticCarryForwardReceipt",
    "BASELINE_FORMAT_KINDS",
    "BASELINE_SOURCE_KINDS",
    "BLOCKED",
    "Base",
    "BaselineAdoption",
    "BaselineFormat",
    "BaselineFormatManifest",
    "BaselineFormatObject",
    "BaselineSource",
    "BaselineSourceRow",
    "CANDIDATE_KINDS",
    "CANDIDATE_STATES",
    "CONFIGURED_ARTIFACT_TYPES",
    "COVERAGE_LINE_STATES",
    "CRITICAL_STRATEGIES",
    "Candidate",
    "CandidateDisposition",
    "ClassBRetentionMixin",
    "CohortReceipt",
    "CommitmentLineage",
    "CommitmentScopeDecision",
    "CommitmentScopeMembership",
    "ConditionResolution",
    "ConnectorCheckpointAdvance",
    "ConnectorCheckpointAdvanceDelivery",
    "CoordinationSummaryConfiguration",
    "CoordinationSummaryRequest",
    "CustomerEnvironmentBinding",
    "DELTA_CHANGE_TYPES",
    "DELTA_DISPOSITIONS",
    "DELTA_EFFECT_KINDS",
    "DELTA_ORGANIZATION_CHANGE_KINDS",
    "DELTA_TARGET_TYPES",
    "DEP_TYPES",
    "DISCOVERED_REFERENCE_STATES",
    "DOC_TYPES",
    "DeltaDecisionSupport",
    "DeltaDeferral",
    "DeltaDisposition",
    "DeltaFollowUpPlan",
    "DeltaFollowUpPlanEvidence",
    "DeltaGroup",
    "DeltaRecordDecision",
    "DeltaReviewPacketChild",
    "DeltaReviewPacketReceipt",
    "DeltaReviewPacketReversal",
    "DeltaReviewPacketSupport",
    "DeltaSupersession",
    "Dependency",
    "DependencyAdmissionOutcome",
    "DependencyDismissal",
    "DependencyEvent",
    "DependencyEventEvidence",
    "DependencyEventMigrationReceipt",
    "DependencyEventScope",
    "DependencyEventScopeDecision",
    "DependencyEventTiming",
    "DependencyEvidenceSufficiency",
    "DiscoveredReference",
    "DisputeHistoryResolution",
    "DisputeSettlement",
    "DocPage",
    "Document",
    "DocumentNotification",
    "DocumentNotificationAttempt",
    "DocumentNotificationDispatch",
    "DocumentQuarantine",
    "DocumentRenditionDerivation",
    "DocumentationFieldConfirmation",
    "DueActionNotification",
    "DueActionNotificationAttempt",
    "DueActionNotificationDispatch",
    "DueWorkOccurrence",
    "DueWorkReceipt",
    "DueWorkSchedule",
    "EVENT_SOURCE_KINDS",
    "EVENT_TYPES",
    "EXTRACTION_OUTCOMES",
    "EventAdmissionAcceptanceReceipt",
    "EventAdmissionActivation",
    "EventAdmissionOutcome",
    "EventCohortReceipt",
    "EvidenceInvestigationCandidateReviewStart",
    "EvidenceInvestigationCaptureContract",
    "EvidenceInvestigationCaptureResult",
    "EvidenceInvestigationEvaluationReceipt",
    "EvidenceInvestigationPacketReceipt",
    "EvidenceInvestigationReviewObservation",
    "EvidenceInvestigationRun",
    "EvidenceInvestigationShadowCase",
    "EvidenceInvestigationShadowExecution",
    "EvidenceInvestigationShadowOutcome",
    "EvidenceInvestigationStepReceipt",
    "EvidenceLink",
    "EvidenceLinkSource",
    "ExternalOrg",
    "ExternalParty",
    "ExternalPartyStatement",
    "ExternalReportArtifact",
    "ExternalReportRelease",
    "ExtractedProposal",
    "ExtractedProposalFact",
    "ExtractionFailureDiagnosisConfiguration",
    "ExtractionFailureDiagnosisRequest",
    "ExtractionMeasurementCaseState",
    "ExtractionRun",
    "ExtractionRunCandidate",
    "ExtractorConfiguration",
    "Fact",
    "FactAppliesTo",
    "FactClosureResult",
    "FactClosureSource",
    "FactDecision",
    "FactDisposition",
    "FactSource",
    "FactStatementTiming",
    "FollowUpPlanReceipt",
    "FollowUpPlanReversal",
    "InboundMessage",
    "InboundRouteTriage",
    "InboundThread",
    "InboundThreadReading",
    "IntakeProjectIdentifier",
    "IssueCoverageDeclaration",
    "IssueProfile",
    "IssueProfileArtifact",
    "KeyDateDraftReceipt",
    "KeyDateDraftRowReceipt",
    "LegacyLedgerArchive",
    "Milestone",
    "MilestoneRegistration",
    "MinutesCapture",
    "NEW_ASSIGNMENT_NOTIFICATION_CATEGORY",
    "NUMBERING_SCHEMES",
    "ORG_TYPES",
    "OperativeSupport",
    "OrganizationIdentityActivation",
    "OrganizationIdentityReceipt",
    "OutgoingRequest",
    "OutgoingRequestResponse",
    "PACKET_CHILD_OUTCOMES",
    "PACKET_GROUPING_KEY_KINDS",
    "PACKET_SEMANTIC_OUTCOMES",
    "PARSE_STATUSES",
    "PLACEHOLDER_PARTIES",
    "POLICY_FAMILIES",
    "PREPARATION_ATTEMPT_OUTCOMES",
    "PREPARATION_REFUSAL_REASONS",
    "PageProcessingFailure",
    "PageRenderDerivative",
    "PersonIdentity",
    "PipelineAcceptance",
    "PipelineComparison",
    "PipelineConfiguration",
    "PipelineObservation",
    "PipelineQualification",
    "PipelineQualificationPolicy",
    "PipelineReceiptMixin",
    "PipelineSelection",
    "PolicyActivation",
    "PolicyApproval",
    "PolicyRun",
    "ProcessingArtifact",
    "ProductionRunExplanationConfiguration",
    "ProductionRunExplanationRequest",
    "Project",
    "ProjectCheckConfiguration",
    "ProjectContact",
    "ProjectContactImport",
    "ProjectRecordRevision",
    "ProjectRosterEntry",
    "ProposedDelta",
    "ProposedDeltaImpactDerivation",
    "PushIntakeCredential",
    "READY",
    "READY_WITH_EXCEPTIONS",
    "RELEASE_READINESS_STATES",
    "RESOLUTION_STRATEGIES",
    "REVISION_COMPARISON_STATES",
    "ReconfirmationReceipt",
    "RecordInclusionRequest",
    "RecordedVerbalOrigin",
    "RecordedVerbalOriginBackfillReceipt",
    "RecordedVerbalOriginFactDigest",
    "RecordedVerbalOriginStatement",
    "ReleaseCandidate",
    "ReleaseCandidateArtifact",
    "ReleasePackage",
    "ReleasePackageArtifact",
    "ReleasePreparationAttempt",
    "ReleasePreparationPublication",
    "ReleasePreparationReading",
    "ReleasePreparationRefusal",
    "ReleasePreparationRequest",
    "ReportRun",
    "RetentionHold",
    "RetentionManifest",
    "RetentionManifestItem",
    "RetentionReference",
    "RetiredDependencyStatus",
    "RevisionChangeExplanationConfiguration",
    "RevisionChangeExplanationRequest",
    "RevisionComparisonFinding",
    "RevisionComparisonRun",
    "RevisionReconciliationRequest",
    "SOURCE_FETCH_OUTCOMES",
    "STATEMENT_ATTRIBUTION_STATES",
    "STATEMENT_SCOPE_MODES",
    "SUPPORT_ASSESSMENT_EVIDENCE_ROLES",
    "SUPPORT_ASSESSMENT_OUTCOMES",
    "SUPPORT_ROLES",
    "ScheduleGoverningDerivation",
    "ScheduleLinkActivation",
    "ScheduleLinkReceipt",
    "ScheduledReportPublication",
    "ShadowProject",
    "ShadowRun",
    "SignInAttempt",
    "SignInToken",
    "SourceDelivery",
    "SourceFactAppendReceipt",
    "SourceFetchAttempt",
    "SourceIntakeDraftConfiguration",
    "SourceIntakeDraftRequest",
    "SourceSegment",
    "StatedByPerson",
    "StatementCoordinationReceipt",
    "StatementCoordinationReversal",
    "StatementCoordinationReversalEffect",
    "StatementEvidence",
    "StatementSuggestionEligibilityDeclaration",
    "StatementSuggestionProtection",
    "StatementSuggestionProtectionEnd",
    "StatementTimingRecord",
    "SubjectCandidateSuggestion",
    "SubjectResolutionAttempt",
    "SubjectResolutionCandidate",
    "SubjectResolutionDecision",
    "SupportAssessment",
    "SupportAssessmentSource",
    "TEXT_SOURCES",
    "TIMING_CHANGE_DIRECTIONS",
    "TIMING_PRECISIONS",
    "TokenLayerManifest",
    "UnreadableCellAdmissionActivation",
    "UnreadableCellReadingProfile",
    "UnreadableCellReadingRun",
    "UnreadableCellReadingStep",
    "UnreadableCellResolution",
    "WebSession",
    "WorkDecision",
    "WorkDecisionMilestoneImpact",
    "is_claim",
    "is_critical",
    "is_placeholder_party",
]
