"""skeleton: projects, documents, dependencies, evidence_links, assertions

Revision ID: 138d897277cf
Revises: 
Create Date: 2026-08-02 22:57:58.566469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '138d897277cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('agency', sa.Text(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('dependencies',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('ref_code', sa.String(length=32), nullable=False),
    sa.Column('dep_type', sa.Enum('utility_relocation', 'agreement', 'permit', 'row', 'railroad', 'access', 'other', name='dep_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('location_desc', sa.Text(), nullable=True),
    sa.Column('station_from', sa.String(length=32), nullable=True),
    sa.Column('station_to', sa.String(length=32), nullable=True),
    sa.Column('external_org_id', sa.BigInteger(), nullable=True),
    sa.Column('milestone_id', sa.BigInteger(), nullable=True),
    sa.Column('external_contact', sa.Text(), nullable=True),
    sa.Column('internal_owner', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('identified', 'in_progress', 'committed', 'blocked', 'closed', name='dep_status', native_enum=False, create_constraint=True), server_default='identified', nullable=False),
    sa.Column('criticality', sa.Enum('critical', 'high', 'normal', name='criticality', native_enum=False, create_constraint=True), server_default='normal', nullable=False),
    sa.Column('committed_date', sa.Date(), nullable=True),
    sa.Column('need_date', sa.Date(), nullable=True),
    sa.Column('evidence_required', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'ref_code')
    )
    op.create_table('documents',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('doc_type', sa.Enum('matrix', 'minutes', 'agreement', 'email', 'plan', 'schedule', 'spec', 'status_report', 'other', name='doc_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('doc_date', sa.Date(), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('parse_status', sa.Enum('pending', 'parsed', 'failed', name='parse_status', native_enum=False, create_constraint=True), server_default='pending', nullable=False),
    sa.Column('superseded_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['superseded_by'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'sha256')
    )
    op.create_table('evidence_links',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('dependency_id', sa.BigInteger(), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('satisfies_requirement', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dependency_id'], ['dependencies.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assertions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('dependency_id', sa.BigInteger(), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=False),
    sa.Column('asserted_value', sa.Text(), nullable=True),
    sa.Column('evidence_link_id', sa.BigInteger(), nullable=False),
    sa.Column('doc_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dependency_id'], ['dependencies.id'], ),
    sa.ForeignKeyConstraint(['evidence_link_id'], ['evidence_links.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assertions')
    op.drop_table('evidence_links')
    op.drop_table('documents')
    op.drop_table('dependencies')
    op.drop_table('projects')
    # ### end Alembic commands ###
