"""add candidates

Revision ID: 2469a1a54fa3
Revises: dec8356300bb
Create Date: 2026-08-02 23:34:52.599495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2469a1a54fa3'
down_revision: Union[str, Sequence[str], None] = 'dec8356300bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.Enum('dependency', 'event', name='candidate_kind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_document_id', sa.BigInteger(), nullable=False),
    sa.Column('source_pages', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('citations_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('state', sa.Enum('pending', 'accepted', 'merged', 'rejected', name='candidate_state', native_enum=False, create_constraint=True), server_default='pending', nullable=False),
    sa.Column('merged_into', sa.BigInteger(), nullable=True),
    sa.Column('adjudicated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merged_into'], ['dependencies.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidates')
    # ### end Alembic commands ###
