"""add dependency_events and evidence_links.event_id

Revision ID: 556cf6d87975
Revises: c61a788b0578
Create Date: 2026-08-03 11:17:29.886855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '556cf6d87975'
down_revision: Union[str, Sequence[str], None] = 'c61a788b0578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dependency_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('dependency_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.Enum('commitment', 'response', 'slip', 'escalation', 'status_change', 'closure', name='event_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dependency_id'], ['dependencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('evidence_links', sa.Column('event_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'evidence_links', 'dependency_events', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'evidence_links', type_='foreignkey')
    op.drop_column('evidence_links', 'event_id')
    op.drop_table('dependency_events')
    # ### end Alembic commands ###
