"""add dependencies.source_ref

Revision ID: aba92563e60e
Revises: 9477fa94ac2c
Create Date: 2026-08-02 23:57:20.161098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aba92563e60e'
down_revision: Union[str, Sequence[str], None] = '9477fa94ac2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dependencies', sa.Column('source_ref', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dependencies', 'source_ref')
    # ### end Alembic commands ###
