"""add doc_pages.text_source

Revision ID: c61a788b0578
Revises: aba92563e60e
Create Date: 2026-08-03 00:59:46.078851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c61a788b0578'
down_revision: Union[str, Sequence[str], None] = 'aba92563e60e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doc_pages', sa.Column('text_source', sa.Enum('text_layer', 'ocr', name='text_source', native_enum=False, create_constraint=True), server_default='text_layer', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doc_pages', 'text_source')
    # ### end Alembic commands ###
