"""Generate docs/adr/INDEX.md, the current-decision index, from ADR frontmatter.

Each ADR carries YAML frontmatter: `status` (accepted, proposed, deprecated,
or `superseded by ADR-NNNN[ and ADR-NNNN]`), `domain`, `scope` (current
product, optional module, historical, future), optional `supersedes`,
`amends`, `amended_by` lists, and an optional `migration` note naming what
is still unresolved. The lifecycle policy is docs/adr/README.md; the
architecture test validates the metadata and that INDEX.md is current.

Usage: `uv run python scripts/adr_index.py` rewrites INDEX.md;
`--check` exits 1 when the file is stale.
"""

from __future__ import annotations

import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
ADR_DIR = REPO_ROOT / "docs" / "adr"
SOURCE_ROOT = REPO_ROOT / "src" / "corridor"
INDEX_PATH = ADR_DIR / "INDEX.md"

STATUS_PATTERN = re.compile(
    r"^(accepted|proposed|deprecated|superseded by ADR-\d{4}(?: and ADR-\d{4})*)$"
)
SCOPES = ("current product", "optional module", "historical", "future")
LIST_KEYS = ("supersedes", "amends", "amended_by")


@dataclass
class Adr:
    number: str
    path: Path
    title: str
    status: str
    domain: str
    scope: str
    supersedes: list[str] = field(default_factory=list)
    amends: list[str] = field(default_factory=list)
    amended_by: list[str] = field(default_factory=list)
    migration: str = ""

    @property
    def ref(self) -> str:
        return f"ADR-{self.number}"

    @property
    def superseded_by(self) -> list[str]:
        return re.findall(r"ADR-\d{4}", self.status) if self.status.startswith("superseded") else []

    @property
    def active(self) -> bool:
        return self.status in ("accepted", "proposed")


def parse_frontmatter(path: Path) -> tuple[dict[str, str | list[str]], list[str]]:
    lines = path.read_text(encoding="utf-8").splitlines()
    if not lines or lines[0] != "---" or "---" not in lines[1:]:
        raise ValueError(f"{path.name}: missing frontmatter")
    end = lines.index("---", 1)
    fm: dict[str, str | list[str]] = {}
    key = None
    for line in lines[1:end]:
        if line.startswith("  - "):
            if key is None or not isinstance(fm.get(key), list):
                raise ValueError(f"{path.name}: list item outside a list")
            fm[key].append(line[4:].strip())
        else:
            key, sep, value = line.partition(":")
            if not sep:
                raise ValueError(f"{path.name}: malformed frontmatter line {line!r}")
            key = key.strip()
            value = value.strip()
            fm[key] = value if value else []
    return fm, lines[end + 1 :]


def load_adrs(adr_dir: Path = ADR_DIR) -> dict[str, Adr]:
    adrs: dict[str, Adr] = {}
    for path in sorted(adr_dir.glob("[0-9][0-9][0-9][0-9]-*.md")):
        fm, body = parse_frontmatter(path)
        title = next((l[2:].strip() for l in body if l.startswith("# ")), path.stem)
        adr = Adr(
            number=path.name[:4],
            path=path,
            title=title,
            status=str(fm.get("status", "")),
            domain=str(fm.get("domain", "")),
            scope=str(fm.get("scope", "")),
            migration=str(fm.get("migration", "")) if fm.get("migration") else "",
        )
        for key in LIST_KEYS:
            value = fm.get(key, [])
            setattr(adr, key, list(value) if isinstance(value, list) else [value])
        adrs[adr.number] = adr
    return adrs


def citing_modules(adrs: dict[str, Adr], source_root: Path = SOURCE_ROOT) -> dict[str, list[str]]:
    """Modules whose source text cites the ADR by number."""
    cited: dict[str, list[str]] = {n: [] for n in adrs}
    for path in sorted(source_root.rglob("*.py")):
        if "migrations" in path.parts:
            continue
        text = path.read_text(encoding="utf-8")
        name = ".".join(path.relative_to(source_root).with_suffix("").parts)
        for number in set(re.findall(r"ADR-(\d{4})", text)):
            if number in cited:
                cited[number].append(name)
    return cited


def _link(adr: Adr) -> str:
    return f"[{adr.ref}]({adr.path.name})"


def _refs(refs: list[str], adrs: dict[str, Adr]) -> str:
    return ", ".join(_link(adrs[r[4:]]) if r[4:] in adrs else r for r in refs) or "—"


def render(adrs: dict[str, Adr], cited: dict[str, list[str]]) -> str:
    out = [
        "# Current-decision index",
        "",
        "Generated by `scripts/adr_index.py` from each ADR's frontmatter; do not edit by hand.",
        "`make adr-index` regenerates it and `make check` fails when it is stale.",
        "The lifecycle rules are in [README.md](README.md).",
        "",
        "## Governing decision per domain",
        "",
        "The latest active ADR in each domain, with every other active ADR in that domain.",
        "",
        "| Domain | Latest governing | Other active |",
        "|---|---|---|",
    ]
    domains = sorted({a.domain for a in adrs.values()})
    for domain in domains:
        active = [a for a in adrs.values() if a.domain == domain and a.active]
        if not active:
            out.append(f"| {domain} | — | — |")
            continue
        latest = max(active, key=lambda a: a.number)
        others = [a for a in active if a is not latest]
        out.append(
            f"| {domain} | {_link(latest)} | "
            f"{', '.join(_link(a) for a in others) or '—'} |"
        )
    out += [
        "",
        "## Active decisions",
        "",
        "| ADR | Title | Domain | Scope | Supersedes | Amends | Amended by | Citing modules | Unresolved migration |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for adr in adrs.values():
        if not adr.active:
            continue
        modules = ", ".join(f"`{m}`" for m in cited[adr.number]) or "—"
        out.append(
            f"| {_link(adr)} | {adr.title} | {adr.domain} | {adr.scope} | "
            f"{_refs(adr.supersedes, adrs)} | {_refs(adr.amends, adrs)} | "
            f"{_refs(adr.amended_by, adrs)} | {modules} | {adr.migration or '—'} |"
        )
    out += [
        "",
        "## Superseded and deprecated decisions",
        "",
        "Retained in sequence as history; never governing.",
        "",
        "| ADR | Title | Status | Domain |",
        "|---|---|---|---|",
    ]
    for adr in adrs.values():
        if adr.active:
            continue
        status = adr.status
        for ref in adr.superseded_by:
            if ref[4:] in adrs:
                status = status.replace(ref, _link(adrs[ref[4:]]))
        out.append(f"| {_link(adr)} | {adr.title} | {status} | {adr.domain} |")
    return "\n".join(out) + "\n"


def main(argv: list[str]) -> int:
    adrs = load_adrs()
    text = render(adrs, citing_modules(adrs))
    if "--check" in argv:
        current = INDEX_PATH.read_text(encoding="utf-8") if INDEX_PATH.exists() else ""
        if current != text:
            print("docs/adr/INDEX.md is stale; run `make adr-index`.", file=sys.stderr)
            return 1
        return 0
    INDEX_PATH.write_text(text, encoding="utf-8")
    print(f"wrote {INDEX_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
