#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — SH 99 Grand Parkway date-cohort approval
# Generated 2026-08-07 from the live database; membership rule: a conflict
# enters if at least one commitment, slip, or closure event that references
# it carries a date.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=40

# Decisions are appended to RESULT_FILE the moment they are made, so a
# Ctrl-C loses nothing: re-running skips every conflict already decided.
# To change a decision, edit the file and re-run.
[[ -t 0 ]] || { printf "This wizard needs an interactive terminal.\n" >&2; exit 1; }
cd "$(cd "$(dirname "$0")/.." && pwd)"
RESULT_FILE="out/sh99-date-cohort-approval.txt"
mkdir -p out
if [[ ! -f "$RESULT_FILE" ]]; then
  {
    echo "# SH 99 date-cohort approval — started $(date +%Y-%m-%d)"
    echo "# rule: >=1 dated commitment/slip/closure event references the conflict"
  } > "$RESULT_FILE"
fi
_prior()  { grep -E "^(approved|excluded) $1\$" "$RESULT_FILE" | tail -n1 | cut -d" " -f1; }
_record() { printf "%s %s\n" "$1" "$2" >> "$RESULT_FILE"; printf "  %s✓ recorded%s %s %s\n" "$GREEN" "$RESET" "$1" "$2"; }

banner "SH 99 date-cohort approval"

stage "The membership rule"
say "37 Grand Parkway conflicts have at least one dated commitment,"
say "slip, or closure event extracted from the meeting minutes."
say ""
say "This wizard shows each conflict with its facts and sample quotes."
say "You include it in the cohort, or you exclude it."
say ""
say "Include means: its Dependency will be admitted through the queue, and"
say "its events become eligible for the policy gate."
say "Exclude means: it stays a pending Candidate. Nothing is lost."
say ""
note "Each decision is saved to $RESULT_FILE the moment you make it."
note "Ctrl-C loses nothing; re-running skips what you already decided."
note "No database writes happen here. Admission itself stays in the queue."
pause

stage "PL34 — Denbury Green Pipeline"
say 'Party: Denbury Green Pipeline   Type: Petroleum and Gaseous Materials'
say 'Events: 37 total, 23 dated commitment/slip/closure, 9 distinct commitment dates, 0 closures'
say ""
note '2024-08-07  LJA committed to provide horizontal and vertical pipeline alignments based on the RODSSUE probes.'
note '2025-03-19  A Standard Utility Agreement is needed for costs incurred to date, while remaining design and reloca'
prior=$(_prior PL34 || true)
if [[ -n "$prior" ]]; then
  note "Already decided on a previous run: $prior PL34 — kept. (Edit $RESULT_FILE to change.)"
elif confirm "Include PL34 in the cohort?"; then
  _record approved PL34
else
  _record excluded PL34
fi

stage "PL06 — Energy Transfer"
say 'Party: Energy Transfer   Type: Petroleum and Gaseous Materials'
say 'Events: 48 total, 18 dated commitment/slip/closure, 9 distinct commitment dates, 3 closures'
say ""
note '2024-08-26  LJA committed to confirm through test holes that the encasement extends from ROW to ROW and to verif'
note '2025-03-24  LJA and Energy Transfer will continue working on a design agreement for the PL06 line remaining in p'
prior=$(_prior PL06 || true)
if [[ -n "$prior" ]]; then
  note "Already decided on a previous run: $prior PL06 — kept. (Edit $RESULT_FILE to change.)"
elif confirm "Include PL06 in the cohort?"; then
  _record approved PL06
else
  _record excluded PL06
fi

stage "PL23 — Enterprise"
say 'Party: Enterprise   Type: Petroleum and Gaseous Materials'
say 'Events: 34 total, 18 dated commitment/slip/closure, 6 distinct commitment dates, 0 closures'
say ""
note '2024-08-08  The plan was to remove the abandoned PL23 line from the proposed TxDOT right of way on Line 15-56.'
note '2025-01-09  LJA will coordinate the PL23 conflict with the landowner.'
prior=$(_prior PL23 || true)
if [[ -n "$prior" ]]; then
  note "Already decided on a previous run: $prior PL23 — kept. (Edit $RESULT_FILE to change.)"
elif confirm "Include PL23 in the cohort?"; then
  _record approved PL23
else
  _record excluded PL23
fi

stage "PL24 — Kinder Morgan Tejas Pipeline"
say 'Party: Kinder Morgan Tejas Pipeline   Type: Petroleum and Gaseous Materials'
say 'Events: 22 total, 16 dated commitment/slip/closure, 9 distinct commitment dates, 1 closures'
say ""
note '2024-08-29  The project team stated that SUE would be upgraded to test holes for PL24.'
note '2025-01-16  Kinder Morgan will verify the existing pipeline alignment in relation to the proposed McFarland Driv'
prior=$(_prior PL24 || true)
if [[ -n "$prior" ]]; then
  note "Already decided on a previous run: $prior PL24 — kept. (Edit $RESULT_FILE to change.)"
elif confirm "Include PL24 in the cohort?"; then
  _record approved PL24
else
  _record excluded PL24
fi

stage "PL35 — Air Products"
say 'Party: Air Products   Type: Petroleum and Gaseous Materials'
say 'Events: 26 total, 16 dated commitment/slip/closure, 6 distinct commitment dates, 5 closures'
say ""
note '2024-08-13  The conflict was considered clear because the line was planned to be outside the construction area.'
note '2025-04-14  Air Products will be invited to the TxDOT-Utility Owners-DB Proposers Workshop, where the DB Contrac'
prior=$(_prior PL35 || true)
if [[ -n "$prior" ]]; then
  note "Already decided on a previous run: $prior PL35 — kept. (Edit $RESULT_FILE to change.)"
elif confirm "Include PL35 in the cohort?"; then
  _record approved PL35
else
  _record excluded PL35
fi

stage "PL36 — Buckeye"
say 'Party: Buckeye   Type: Petroleum and Gaseous Materials'
say 'Events: 40 total, 16 dated commitment/slip/closure, 8 distinct commitment dates, 0 closures'
say ""
note '2024-08-27  Buckeye committed to provide the Barlow calculation for the existing line to determine whether it ca'
note '2025-03-25  LJA committed to invite Buckeye representatives to the TxDOT-Utility Owners-DB Proposers Workshop sc'
prior=$(_prior PL36 || true)
if [[ -n "$prior" ]]; then
  note "Already decided on a previous run: $prior PL36 — kept. (Edit $RESULT_FILE to change.)"
elif confirm "Include PL36 in the cohort?"; then
  _record approved PL36
else
  _record excluded PL36
fi

stage "PL28 — Energy Transfer"
say 'Party: Energy Transfer   Type: Petroleum and Gaseous Materials'
say 'Events: 44 total, 14 dated commitment/slip/closure, 8 distinct commitment dates, 0 closures'
say ""
note '2024-09-09  LJA stated that it would provide updated drainage and cross sections for PL28.'
note '2025-01-13  LJA will provide updated drainage information and cross sections for PL28.'
prior=$(_prior PL28 || true)
if [[ -n "$prior" ]]; then
  note "Already decided on a previous run: $prior PL28 — kept. (Edit $RESULT_FILE to change.)"
elif confirm "Include PL28 in the cohort?"; then
  _record approved PL28
else
  _record excluded PL28
fi

stage "PL03 — Florida Gas Transmission"
say 'Party: Florida Gas Transmission   Type: Petroleum and Gaseous Materials'
say 'Events: 46 total, 12 dated commitment/slip/closure, 7 distinct commitment dates, 0 closures'
say ""
note '2024-10-07  Updated cross sections showing the drainage basins at Johnson St. are needed.'
note '2025-01-13  LJA committed to obtain updated cross sections at PL03 Johnson Street showing the drainage basins.'
prior=$(_prior PL03 || true)
if [[ -n "$prior" ]]; then
  note "Already decided on a previous run: $prior PL03 — kept. (Edit $RESULT_FILE to change.)"
elif confirm "Include PL03 in the cohort?"; then
  _record approved PL03
else
  _record excluded PL03
fi

stage "PL21 — Enterprise"
say 'Party: Enterprise   Type: Petroleum and Gaseous Materials'
say 'Events: 28 total, 11 dated commitment/slip/closure, 6 distinct commitment dates, 0 closures'
say ""
note '2024-08-08  Enterprise committed to provide XYZ coordinates for the active PL21 pipeline.'
note '2025-03-06  Enterprise committed to produce the design for the necessary adjustments to PL21 on Line 15.'
prior=$(_prior PL21 || true)
if [[ -n "$prior" ]]; then
  note "Already decided on a previous run: $prior PL21 — kept. (Edit $RESULT_FILE to change.)"
elif confirm "Include PL21 in the cohort?"; then
  _record approved PL21
else
  _record excluded PL21
fi

stage "PL51 — Kinder Morgan Tejas Pipeline"
say 'Party: Kinder Morgan Tejas Pipeline   Type: Petroleum and Gaseous Materials'
say 'Events: 18 total, 11 dated commitment/slip/closure, 8 distinct commitment dates, 0 closures'
say ""
note '2024-08-02  LJA committed to obtain updated cross sections at the Gang of 11 and provide them to Kinder Morgan.'
note '2025-01-16  Joshua Amador will research the request for a LONO related to the legacy offsite drainage and valve '
prior=$(_prior PL51 || true)
if [[ -n "$prior" ]]; then
  note "Already decided on a previous run: $prior PL51 — kept. (Edit $RESULT_FILE to change.)"
elif confirm "Include PL51 in the cohort?"; then
  _record approved PL51
else
  _record excluded PL51
fi

stage "PL45 — Energy Transfer"
say 'Party: Energy Transfer   Type: Petroleum and Gaseous Materials'
say 'Events: 39 total, 10 dated commitment/slip/closure, 8 distinct commitment dates, 0 closures'
say ""
note '2024-08-12  Energy Transfer committed to verify whether the easternmost 4-inch line can be idled.'
note '2025-01-13  LJA committed to obtain the updated cross section for PL45 at station 6723+30, aligned with the Ener'
prior=$(_prior PL45 || true)
if [[ -n "$prior" ]]; then
  note "Already decided on a previous run: $prior PL45 — kept. (Edit $RESULT_FILE to change.)"
elif confirm "Include PL45 in the cohort?"; then
  _record approved PL45
else
  _record excluded PL45
fi

stage "PL30 — Energy Transfer"
say 'Party: Energy Transfer   Type: Petroleum and Gaseous Materials'
say 'Events: 39 total, 9 dated commitment/slip/closure, 6 distinct commitment dates, 0 closures'
say ""
note '2024-09-09  LJA stated that it would provide updated drainage and cross sections for PL30.'
note '2025-01-13  LJA committed to provide updated cross sections and drainage information for the PL30 conflict affec'
prior=$(_prior PL30 || true)
if [[ -n "$prior" ]]; then
  note "Already decided on a previous run: $prior PL30 — kept. (Edit $RESULT_FILE to change.)"
elif confirm "Include PL30 in the cohort?"; then
  _record approved PL30
else
  _record excluded PL30
fi

stage "PL44 — DOW"
say 'Party: DOW   Type: Petroleum and Gaseous Materials'
say 'Events: 23 total, 9 dated commitment/slip/closure, 5 distinct commitment dates, 0 closures'
say ""
note '2025-01-09  DOW will provide a typical concrete slab detail for inclusion in the Design Build contract.'
note '2025-03-20  DOW stated it will provide a typical detail for the adjustment required because PL44 has shallow cov'
prior=$(_prior PL44 || true)
if [[ -n "$prior" ]]; then
  note "Already decided on a previous run: $prior PL44 — kept. (Edit $RESULT_FILE to change.)"
elif confirm "Include PL44 in the cohort?"; then
  _record approved PL44
else
  _record excluded PL44
fi

stage "PL14 — Chevron"
say 'Party: Chevron   Type: Petroleum and Gaseous Materials'
say 'Events: 27 total, 8 dated commitment/slip/closure, 5 distinct commitment dates, 0 closures'
say ""
note '2024-09-18  Jason said he would check whether probe and test lead methods could be coordinated if hydro-vac work'
note '2025-02-05  The parties agreed to determine the pipe elevation at the ditch before deciding whether PL14 will be'
prior=$(_prior PL14 || true)
if [[ -n "$prior" ]]; then
  note "Already decided on a previous run: $prior PL14 — kept. (Edit $RESULT_FILE to change.)"
elif confirm "Include PL14 in the cohort?"; then
  _record approved PL14
else
  _record excluded PL14
fi

stage "PL29 — Kinder Morgan Tejas Pipeline"
say 'Party: Kinder Morgan Tejas Pipeline   Type: Petroleum and Gaseous Materials'
say 'Events: 19 total, 8 dated commitment/slip/closure, 5 distinct commitment dates, 0 closures'
say ""
note '2024-11-07  LJA committed to provide Kinder Morgan with the League City water-line easement for the Bay Area Bou'
note '2025-04-10  LJA committed to provide an updated cross section for PL29 near Bay Area Blvd.'
prior=$(_prior PL29 || true)
if [[ -n "$prior" ]]; then
  note "Already decided on a previous run: $prior PL29 — kept. (Edit $RESULT_FILE to change.)"
elif confirm "Include PL29 in the cohort?"; then
  _record approved PL29
else
  _record excluded PL29
fi

stage "PL41 — Air Liquide"
say 'Party: Air Liquide   Type: Petroleum and Gaseous Materials'
say 'Events: 27 total, 8 dated commitment/slip/closure, 5 distinct commitment dates, 0 closures'
say ""
note '2024-08-26  Air Liquide was assigned to provide or verify the survey pipe elevation.'
note '2025-01-13  Air Liquide said it would follow up on whether it wants to pursue reimbursement for PL41.'
prior=$(_prior PL41 || true)
if [[ -n "$prior" ]]; then
  note "Already decided on a previous run: $prior PL41 — kept. (Edit $RESULT_FILE to change.)"
elif confirm "Include PL41 in the cohort?"; then
  _record approved PL41
else
  _record excluded PL41
fi

stage "PL27 — Kinder Morgan Tejas Pipeline"
say 'Party: Kinder Morgan Tejas Pipeline   Type: Petroleum and Gaseous Materials'
say 'Events: 14 total, 7 dated commitment/slip/closure, 7 distinct commitment dates, 0 closures'
say ""
note '2024-08-29  Joshua Amador committed to research the request for a LONO related to Legacy offsite drainage.'
note '2025-01-16  Joshua Amador will research the request for a LONO related to the legacy offsite drainage and valve '
prior=$(_prior PL27 || true)
if [[ -n "$prior" ]]; then
  note "Already decided on a previous run: $prior PL27 — kept. (Edit $RESULT_FILE to change.)"
elif confirm "Include PL27 in the cohort?"; then
  _record approved PL27
else
  _record excluded PL27
fi

stage "ET13 — CenterPoint Energy (Electric Transmission)"
say 'Party: CenterPoint Energy (Electric Transmission)   Type: Electric'
say 'Events: 13 total, 6 dated commitment/slip/closure, 3 distinct commitment dates, 0 closures'
say ""
note '2024-08-06  LJA committed to prepare the clearance letter for the ET13 crossing at Steele Road.'
note '2024-09-24  CenterPoint committed to provide an email affirming that ET13 at Steele Road is not believed to conf'
prior=$(_prior ET13 || true)
if [[ -n "$prior" ]]; then
  note "Already decided on a previous run: $prior ET13 — kept. (Edit $RESULT_FILE to change.)"
elif confirm "Include ET13 in the cohort?"; then
  _record approved ET13
else
  _record excluded ET13
fi

stage "PL17 — Chevron"
say 'Party: Chevron   Type: Petroleum and Gaseous Materials'
say 'Events: 24 total, 6 dated commitment/slip/closure, 3 distinct commitment dates, 0 closures'
say ""
note '2024-08-07  Chevron stated it would discuss options with CPChem regarding the pipeline conflict.'
note '2024-10-31  TxDOT stated it will acquire the property while leaving Chevron’s easement in place, and LJA will co'
prior=$(_prior PL17 || true)
if [[ -n "$prior" ]]; then
  note "Already decided on a previous run: $prior PL17 — kept. (Edit $RESULT_FILE to change.)"
elif confirm "Include PL17 in the cohort?"; then
  _record approved PL17
else
  _record excluded PL17
fi

stage "PL22 — Energy Transfer"
say 'Party: Energy Transfer   Type: Petroleum and Gaseous Materials'
say 'Events: 33 total, 6 dated commitment/slip/closure, 4 distinct commitment dates, 0 closures'
say ""
note '2024-11-04  LJA committed to obtain updated cross sections from 6404+00 to 6425+00 for PL22.'
note '2025-01-13  LJA committed to obtain updated cross sections for PL22 from station 6404+00 through 6425+00.'
prior=$(_prior PL22 || true)
if [[ -n "$prior" ]]; then
  note "Already decided on a previous run: $prior PL22 — kept. (Edit $RESULT_FILE to change.)"
elif confirm "Include PL22 in the cohort?"; then
  _record approved PL22
else
  _record excluded PL22
fi

stage "PL20 — Equistar"
say 'Party: Equistar   Type: Petroleum and Gaseous Materials'
say 'Events: 13 total, 4 dated commitment/slip/closure, 3 distinct commitment dates, 0 closures'
say ""
note '2024-09-25  Equistar was to notify LJA if any moratoriums or outage restrictions existed on the pipeline.'
note '2025-01-29  Equistar committed to research whether as-built documentation exists for the siphon ditch.'
prior=$(_prior PL20 || true)
if [[ -n "$prior" ]]; then
  note "Already decided on a previous run: $prior PL20 — kept. (Edit $RESULT_FILE to change.)"
elif confirm "Include PL20 in the cohort?"; then
  _record approved PL20
else
  _record excluded PL20
fi

stage "PL31 — Kinder Morgan Tejas Pipeline"
say 'Party: Kinder Morgan Tejas Pipeline   Type: Petroleum and Gaseous Materials'
say 'Events: 11 total, 4 dated commitment/slip/closure, 3 distinct commitment dates, 0 closures'
say ""
note '2024-11-07  Kinder Morgan was directed to begin and currently progress an easement study for the PL31 conflict a'
note '2025-01-02  Kinder Morgan was directed to begin and immediately progress an easement study for PL31, which runs '
prior=$(_prior PL31 || true)
if [[ -n "$prior" ]]; then
  note "Already decided on a previous run: $prior PL31 — kept. (Edit $RESULT_FILE to change.)"
elif confirm "Include PL31 in the cohort?"; then
  _record approved PL31
else
  _record excluded PL31
fi

stage "PL49 — Kinder Morgan Tejas Pipeline"
say 'Party: Kinder Morgan Tejas Pipeline   Type: Petroleum and Gaseous Materials'
say 'Events: 10 total, 4 dated commitment/slip/closure, 3 distinct commitment dates, 1 closures'
say ""
note '2024-08-29  Test hole 199 was planned in the PL49 area.'
note '2024-12-04  LJA committed to provide the Maple Leaf Drive cross section for PL49.'
prior=$(_prior PL49 || true)
if [[ -n "$prior" ]]; then
  note "Already decided on a previous run: $prior PL49 — kept. (Edit $RESULT_FILE to change.)"
elif confirm "Include PL49 in the cohort?"; then
  _record approved PL49
else
  _record excluded PL49
fi

stage "PL38 — Energy Transfer"
say 'Party: Energy Transfer   Type: Petroleum and Gaseous Materials'
say 'Events: 35 total, 3 dated commitment/slip/closure, 3 distinct commitment dates, 0 closures'
say ""
note '2024-10-07  LJA will prepare the TxDOT CFUA form with project information for PL38, along with the other listed '
note '2025-03-24  Energy Transfer was asked to include PL38 in its survey because of the turn and proposed sound barri'
prior=$(_prior PL38 || true)
if [[ -n "$prior" ]]; then
  note "Already decided on a previous run: $prior PL38 — kept. (Edit $RESULT_FILE to change.)"
elif confirm "Include PL38 in the cohort?"; then
  _record approved PL38
else
  _record excluded PL38
fi

stage "PL42 — DOW"
say 'Party: DOW   Type: Petroleum and Gaseous Materials'
say 'Events: 7 total, 3 dated commitment/slip/closure, 2 distinct commitment dates, 0 closures'
say ""
note '2024-08-08  PL42 will be coordinated through Air Liquide.'
note '2024-09-23  LJA committed to follow up with RODSSUE regarding PL41 and PL42 being represented as a single line a'
prior=$(_prior PL42 || true)
if [[ -n "$prior" ]]; then
  note "Already decided on a previous run: $prior PL42 — kept. (Edit $RESULT_FILE to change.)"
elif confirm "Include PL42 in the cohort?"; then
  _record approved PL42
else
  _record excluded PL42
fi

stage "PL50 — Energy Transfer"
say 'Party: Energy Transfer   Type: Petroleum and Gaseous Materials'
say 'Events: 27 total, 3 dated commitment/slip/closure, 3 distinct commitment dates, 0 closures'
say ""
note '2024-12-16  LJA and Energy Transfer were to work on a design agreement for protecting PL50 in place.'
note '2025-03-24  LJA and Energy Transfer will work on a design agreement for protecting PL50 in place.'
prior=$(_prior PL50 || true)
if [[ -n "$prior" ]]; then
  note "Already decided on a previous run: $prior PL50 — kept. (Edit $RESULT_FILE to change.)"
elif confirm "Include PL50 in the cohort?"; then
  _record approved PL50
else
  _record excluded PL50
fi

stage "PL09 — Enterprise"
say 'Party: Enterprise   Type: Petroleum and Gaseous Materials'
say 'Events: 13 total, 2 dated commitment/slip/closure, 2 distinct commitment dates, 1 closures'
say ""
note '2024-08-08  The team planned to leave PL09 abandoned in place and Enterprise will confirm whether it is grout fi'
note '2024-09-05  Enterprise will research the PL09 abandonment, confirm whether it was grout filled, and provide avai'
prior=$(_prior PL09 || true)
if [[ -n "$prior" ]]; then
  note "Already decided on a previous run: $prior PL09 — kept. (Edit $RESULT_FILE to change.)"
elif confirm "Include PL09 in the cohort?"; then
  _record approved PL09
else
  _record excluded PL09
fi

stage "PL25 — ExxonMobil"
say 'Party: ExxonMobil   Type: Petroleum and Gaseous Materials'
say 'Events: 3 total, 2 dated commitment/slip/closure, 2 distinct commitment dates, 0 closures'
say ""
note '2024-08-14  LJA committed to follow up with the road design team regarding the bridge bent location affecting th'
note '2024-09-25  LJA committed to share probe-depth information for the PL25 line.'
prior=$(_prior PL25 || true)
if [[ -n "$prior" ]]; then
  note "Already decided on a previous run: $prior PL25 — kept. (Edit $RESULT_FILE to change.)"
elif confirm "Include PL25 in the cohort?"; then
  _record approved PL25
else
  _record excluded PL25
fi

stage "PL43 — Shell Pipeline"
say 'Party: Shell Pipeline   Type: Petroleum and Gaseous Materials'
say 'Events: 11 total, 2 dated commitment/slip/closure, 1 distinct commitment dates, 0 closures'
say ""
note '2024-10-24  LJA will assist with an exception request for PL43 if one is needed.'
prior=$(_prior PL43 || true)
if [[ -n "$prior" ]]; then
  note "Already decided on a previous run: $prior PL43 — kept. (Edit $RESULT_FILE to change.)"
elif confirm "Include PL43 in the cohort?"; then
  _record approved PL43
else
  _record excluded PL43
fi

stage "ET31 — CenterPoint Energy (Electric Transmission)"
say 'Party: CenterPoint Energy (Electric Transmission)   Type: Electric'
say 'Events: 14 total, 1 dated commitment/slip/closure, 1 distinct commitment dates, 0 closures'
say ""
note '2025-01-14  CNPE committed to provide the tower and pole structure plan view so the design team can provide acce'
prior=$(_prior ET31 || true)
if [[ -n "$prior" ]]; then
  note "Already decided on a previous run: $prior ET31 — kept. (Edit $RESULT_FILE to change.)"
elif confirm "Include ET31 in the cohort?"; then
  _record approved ET31
else
  _record excluded ET31
fi

stage "PL08 — ExxonMobil"
say 'Party: ExxonMobil   Type: Petroleum and Gaseous Materials'
say 'Events: 3 total, 1 dated commitment/slip/closure, 0 distinct commitment dates, 1 closures'
say ""
note '2024-07-31  ExxonMobil confirmed that the PL08 line is abandoned.'
prior=$(_prior PL08 || true)
if [[ -n "$prior" ]]; then
  note "Already decided on a previous run: $prior PL08 — kept. (Edit $RESULT_FILE to change.)"
elif confirm "Include PL08 in the cohort?"; then
  _record approved PL08
else
  _record excluded PL08
fi

stage "PL15 — Phillips66"
say 'Party: Phillips66   Type: Petroleum and Gaseous Materials'
say 'Events: 9 total, 1 dated commitment/slip/closure, 1 distinct commitment dates, 0 closures'
say ""
note '2025-02-05  The abandoned PL15 line was identified for removal.'
prior=$(_prior PL15 || true)
if [[ -n "$prior" ]]; then
  note "Already decided on a previous run: $prior PL15 — kept. (Edit $RESULT_FILE to change.)"
elif confirm "Include PL15 in the cohort?"; then
  _record approved PL15
else
  _record excluded PL15
fi

stage "PL19 — Equistar"
say 'Party: Equistar   Type: Petroleum and Gaseous Materials'
say 'Events: 12 total, 1 dated commitment/slip/closure, 1 distinct commitment dates, 0 closures'
say ""
note '2024-09-25  Equistar was to notify LJA if any moratoriums or outage restrictions existed on the pipeline.'
prior=$(_prior PL19 || true)
if [[ -n "$prior" ]]; then
  note "Already decided on a previous run: $prior PL19 — kept. (Edit $RESULT_FILE to change.)"
elif confirm "Include PL19 in the cohort?"; then
  _record approved PL19
else
  _record excluded PL19
fi

stage "PL53 — Enterprise"
say 'Party: Enterprise   Type: Petroleum and Gaseous Materials'
say 'Events: 2 total, 1 dated commitment/slip/closure, 0 distinct commitment dates, 1 closures'
say ""
note '2024-08-08  PL53 was identified as approximately 50 to 80 feet deep and clear of proposed road construction, so '
prior=$(_prior PL53 || true)
if [[ -n "$prior" ]]; then
  note "Already decided on a previous run: $prior PL53 — kept. (Edit $RESULT_FILE to change.)"
elif confirm "Include PL53 in the cohort?"; then
  _record approved PL53
else
  _record excluded PL53
fi

stage "PL54 — Enterprise"
say 'Party: Enterprise   Type: Petroleum and Gaseous Materials'
say 'Events: 2 total, 1 dated commitment/slip/closure, 0 distinct commitment dates, 1 closures'
say ""
note '2024-08-08  PL54 was identified as approximately 50 to 80 feet deep and clear of proposed road construction, so '
prior=$(_prior PL54 || true)
if [[ -n "$prior" ]]; then
  note "Already decided on a previous run: $prior PL54 — kept. (Edit $RESULT_FILE to change.)"
elif confirm "Include PL54 in the cohort?"; then
  _record approved PL54
else
  _record excluded PL54
fi

stage "PL55 — Enterprise"
say 'Party: Enterprise   Type: Petroleum and Gaseous Materials'
say 'Events: 2 total, 1 dated commitment/slip/closure, 0 distinct commitment dates, 1 closures'
say ""
note '2024-08-08  PL55 was identified as approximately 50 to 80 feet deep and clear of proposed road construction, so '
prior=$(_prior PL55 || true)
if [[ -n "$prior" ]]; then
  note "Already decided on a previous run: $prior PL55 — kept. (Edit $RESULT_FILE to change.)"
elif confirm "Include PL55 in the cohort?"; then
  _record approved PL55
else
  _record excluded PL55
fi

stage "PL65 — Enterprise"
say 'Party: Enterprise   Type: Petroleum and Gaseous Materials'
say 'Events: 3 total, 1 dated commitment/slip/closure, 0 distinct commitment dates, 2 closures'
say ""
note '2025-04-03  LJA completed the action to send Enterprise the cross section showing the fill east of the Steele Ro'
prior=$(_prior PL65 || true)
if [[ -n "$prior" ]]; then
  note "Already decided on a previous run: $prior PL65 — kept. (Edit $RESULT_FILE to change.)"
elif confirm "Include PL65 in the cohort?"; then
  _record approved PL65
else
  _record excluded PL65
fi

stage "The three slips — for context, no decision here"
say "These verified slip events carry no conflict reference. They will"
say "fall to Adjudication, where you attach each to a Dependency by hand."
say ""
note '[7296] Kinder Morgan: Kinder Morgan stated that the March 2026 completion timeline appears unattainable and proposed extending it to May 16.'
note '[7306] Kinder Morgan: A schedule was pushed to June 2026, contingent on receiving drawings in a timely manner.'
note '[7554] Enterprise: The ROW and utility agreement execution milestone moved from July 2025 to April 2026, with Parcel 120 needed.'
pause

stage "Review the decisions"
n_app=$(grep -c "^approved " "$RESULT_FILE" || true)
n_exc=$(grep -c "^excluded " "$RESULT_FILE" || true)
say "Approved: $n_app   Excluded: $n_exc   (of 37 proposed)"
say ""
say "Every decision is in $RESULT_FILE."
note "Hand this file back to the agent to fold into the plan."
note "To change a decision: edit the file, or delete its line and re-run."
pause "Done — press Enter to finish."

finish
