-- Per-constraint and per-index normalisation (#548).
-- pg_dump expands `col IN (…)` into an explicit comparison, and PostgreSQL
-- stores that expansion differently on the way back, so a dump-built schema
-- diverges from the chain-built one on exactly these objects: twenty-nine
-- check constraints and one partial index predicate. Only the IN form
-- stores the canonical expression, so each is re-created with it.
alter table public."extraction_runs" drop constraint "ck_extraction_runs_completed_row_accounting";
alter table public."extraction_runs" add constraint "ck_extraction_runs_completed_row_accounting" check (NOT (outcome::text = 'completed'::text AND (prompt_version IN ('sheet_native_v2', 'matrix_tiered_v4', 'prose_interpretation_v1'))) OR row_accounting_json IS NOT NULL AND ((row_accounting_json ->> 'schema_version'::text) = 'matrix-row-accounting-v1'::text AND jsonb_array_length(row_accounting_json -> 'unaccounted_rows'::text) = 0 AND ((row_accounting_json ->> 'accounted_row_count'::text)::integer) = ((row_accounting_json ->> 'detected_row_count'::text)::integer) AND ((row_accounting_json ->> 'extracted_row_count'::text)::integer) = candidate_count OR (row_accounting_json ->> 'schema_version'::text) = 'prose-segment-accounting-v1'::text AND ((row_accounting_json ->> 'proposed_fact_count'::text)::integer) = candidate_count));
alter table public."fact_closure_results" drop constraint "ck_fact_closure_result_kind";
alter table public."fact_closure_results" add constraint "ck_fact_closure_result_kind" check (closure_kind IN ('source_marked_resolved', 'constraint_closed', 'constraint_remains_open'));
alter table public."fact_decisions" drop constraint "ck_fact_decision_disposition";
alter table public."fact_decisions" add constraint "ck_fact_decision_disposition" check (disposition IN ('include', 'do_not_add', 'restore'));
alter table public."fact_sources" drop constraint "ck_fact_sources_role";
alter table public."fact_sources" add constraint "ck_fact_sources_role" check (role IN ('value_source', 'context', 'attribution_source'));
alter table public."fact_statement_timings" drop constraint "ck_fact_statement_timing_precision";
alter table public."fact_statement_timings" add constraint "ck_fact_statement_timing_precision" check ("precision" IN ('day', 'month', 'approximate'));
alter table public."fact_statement_timings" drop constraint "ck_fact_statement_timing_role";
alter table public."fact_statement_timings" add constraint "ck_fact_statement_timing_role" check (timing_role IN ('previous', 'new'));
alter table public."facts" drop constraint "ck_facts_source_binding";
alter table public."facts" add constraint "ck_facts_source_binding" check (document_id IS NOT NULL AND extraction_run_id IS NOT NULL AND (fact_type NOT IN ('statement_timing', 'supporting_documentation_in_use')) OR document_id IS NULL AND extraction_run_id IS NULL AND (fact_type IN ('statement_wording', 'statement_timing', 'applies_to', 'supporting_documentation_in_use')));
alter table public."facts" drop constraint "ck_facts_subject";
alter table public."facts" add constraint "ck_facts_subject" check ((fact_type IN ('utility_id', 'external_org', 'external_org_contact', 'utility_type', 'utility_subtype', 'utility_function', 'operational_status', 'size', 'material', 'oh_ug', 'row_placement', 'orientation', 'baseline', 'station_from', 'station_to', 'offset_from', 'offset_to', 'sue_level', 'conflict_description', 'resolution_strategy', 'notes', 'alignment', 'location_start', 'location_end', 'offset_side', 'potential_conflict', 'data_source', 'marked_resolution', 'committed_date', 'action_due_date', 'need_date')) AND subject_kind::text = 'source_row'::text AND length(TRIM(BOTH FROM subject_key)) > 0 OR (fact_type IN ('applies_to', 'closure_result')) AND subject_kind::text = 'source_row'::text AND length(TRIM(BOTH FROM subject_key)) > 0 OR (fact_type IN ('statement_wording', 'statement_timing', 'applies_to')) AND subject_kind::text = 'statement_candidate'::text AND length(TRIM(BOTH FROM subject_key)) > 0 OR fact_type::text = 'supporting_documentation_in_use'::text AND subject_kind::text = 'record_subject'::text AND length(TRIM(BOTH FROM subject_key)) > 0);
alter table public."facts" drop constraint "ck_facts_type";
alter table public."facts" add constraint "ck_facts_type" check (fact_type IN ('utility_id', 'external_org', 'external_org_contact', 'utility_type', 'utility_subtype', 'utility_function', 'operational_status', 'size', 'material', 'oh_ug', 'row_placement', 'orientation', 'baseline', 'station_from', 'station_to', 'offset_from', 'offset_to', 'sue_level', 'conflict_description', 'resolution_strategy', 'notes', 'alignment', 'location_start', 'location_end', 'offset_side', 'potential_conflict', 'data_source', 'marked_resolution', 'committed_date', 'action_due_date', 'need_date', 'applies_to', 'closure_result', 'statement_wording', 'statement_timing', 'supporting_documentation_in_use'));
alter table public."facts" drop constraint "ck_facts_typed_value";
alter table public."facts" add constraint "ck_facts_typed_value" check ((fact_type IN ('utility_id', 'external_org', 'external_org_contact', 'utility_type', 'utility_subtype', 'utility_function', 'operational_status', 'size', 'material', 'oh_ug', 'row_placement', 'orientation', 'baseline', 'station_from', 'station_to', 'offset_from', 'offset_to', 'sue_level', 'conflict_description', 'resolution_strategy', 'notes', 'alignment', 'location_start', 'location_end', 'offset_side', 'potential_conflict', 'data_source', 'marked_resolution')) AND text_value IS NOT NULL AND length(TRIM(BOTH FROM text_value)) > 0 AND date_value IS NULL AND date_range_start IS NULL AND date_range_end IS NULL AND (fact_type::text = 'external_org'::text OR external_org_value_id IS NULL) AND document_value_id IS NULL AND transformation::text = 'trim_cell_text_v1'::text OR (fact_type IN ('committed_date', 'action_due_date', 'need_date')) AND text_value IS NULL AND date_value IS NOT NULL AND date_range_start IS NULL AND date_range_end IS NULL AND external_org_value_id IS NULL AND document_value_id IS NULL AND transformation::text = 'iso_date_cell_v1'::text OR fact_type::text = 'applies_to'::text AND text_value IS NULL AND date_value IS NULL AND date_range_start IS NULL AND date_range_end IS NULL AND external_org_value_id IS NULL AND document_value_id IS NULL AND transformation::text = 'structured_reference_set_v1'::text OR fact_type::text = 'closure_result'::text AND text_value IS NULL AND date_value IS NULL AND date_range_start IS NULL AND date_range_end IS NULL AND external_org_value_id IS NULL AND document_value_id IS NULL AND transformation::text = 'typed_closure_result_v1'::text OR fact_type::text = 'statement_wording'::text AND text_value IS NOT NULL AND length(TRIM(BOTH FROM text_value)) > 0 AND date_value IS NULL AND date_range_start IS NULL AND date_range_end IS NULL AND external_org_value_id IS NULL AND document_value_id IS NULL AND transformation::text = 'exact_prose_span_v1'::text OR fact_type::text = 'statement_timing'::text AND text_value IS NULL AND date_value IS NULL AND date_range_start IS NULL AND date_range_end IS NULL AND external_org_value_id IS NULL AND document_value_id IS NULL AND transformation::text = 'typed_statement_timing_v1'::text OR fact_type::text = 'supporting_documentation_in_use'::text AND text_value IS NULL AND date_value IS NULL AND date_range_start IS NULL AND date_range_end IS NULL AND external_org_value_id IS NULL AND document_value_id IS NOT NULL AND transformation::text = 'supporting_document_revision_v1'::text);
alter table public."extraction_failure_diagnosis_configurations" drop constraint "ck_failure_diagnosis_config_retention";
alter table public."extraction_failure_diagnosis_configurations" add constraint "ck_failure_diagnosis_config_retention" check (retention_policy IN ('retained_indefinitely', 'class_b_30_days'));
alter table public."source_intake_draft_configurations" drop constraint "ck_intake_draft_config_retention";
alter table public."source_intake_draft_configurations" add constraint "ck_intake_draft_config_retention" check (retention_policy IN ('retained_indefinitely', 'class_b_30_days'));
alter table public."processing_artifacts" drop constraint "ck_processing_artifact_kind";
alter table public."processing_artifacts" add constraint "ck_processing_artifact_kind" check (kind IN ('page_render', 'raw_ocr', 'token_layer', 'alternate_table_hypothesis', 'unselected_model_response', 'copied_prompt_context', 'agent_trace', 'evaluation_working_data', 'abandoned_report_preparation'));
alter table public."retention_manifests" drop constraint "ck_retention_manifest_status";
alter table public."retention_manifests" add constraint "ck_retention_manifest_status" check (status IN ('dry_run', 'executed', 'refused'));
alter table public."retention_references" drop constraint "ck_retention_reference_kind";
alter table public."retention_references" add constraint "ck_retention_reference_kind" check (kind IN ('segment', 'decision', 'review', 'release', 'processing_failure'));
alter table public."revision_change_explanation_configurations" drop constraint "ck_rev_change_expl_cfg_retention";
alter table public."revision_change_explanation_configurations" add constraint "ck_rev_change_expl_cfg_retention" check (retention_policy IN ('retained_indefinitely', 'class_b_30_days'));
alter table public."production_run_explanation_configurations" drop constraint "ck_run_explanation_config_retention";
alter table public."production_run_explanation_configurations" add constraint "ck_run_explanation_config_retention" check (retention_policy IN ('retained_indefinitely', 'class_b_30_days'));
alter table public."source_segments" drop constraint "ck_source_segments_kind";
alter table public."source_segments" add constraint "ck_source_segments_kind" check (kind IN ('spreadsheet_cell', 'prose_span', 'recorded_verbal_statement'));
alter table public."subject_resolution_candidates" drop constraint "ck_subject_resolution_candidate_match_source";
alter table public."subject_resolution_candidates" add constraint "ck_subject_resolution_candidate_match_source" check (match_source IN ('registered_alias', 'human_alias_decision'));
alter table public."subject_resolution_candidates" drop constraint "ck_subject_resolution_candidate_state";
alter table public."subject_resolution_candidates" add constraint "ck_subject_resolution_candidate_state" check (candidate_state IN ('active', 'stale'));
alter table public."subject_resolution_candidates" drop constraint "ck_subject_resolution_candidate_type";
alter table public."subject_resolution_candidates" add constraint "ck_subject_resolution_candidate_type" check (subject_type IN ('external_org', 'person', 'constraint', 'document'));
alter table public."subject_resolution_decisions" drop constraint "ck_subject_resolution_decision_reference_kind";
alter table public."subject_resolution_decisions" add constraint "ck_subject_resolution_decision_reference_kind" check (reference_kind IN ('organization_name', 'email_sender', 'email_domain', 'person_name', 'person_email', 'source_identifier', 'activity_identifier', 'document_identifier'));
alter table public."subject_resolution_decisions" drop constraint "ck_subject_resolution_decision_type";
alter table public."subject_resolution_decisions" add constraint "ck_subject_resolution_decision_type" check (subject_type IN ('external_org', 'person', 'constraint', 'document'));
alter table public."subject_resolution_attempts" drop constraint "ck_subject_resolution_expected_type";
alter table public."subject_resolution_attempts" add constraint "ck_subject_resolution_expected_type" check (expected_subject_type IN ('external_org', 'person', 'constraint', 'document'));
alter table public."subject_resolution_attempts" drop constraint "ck_subject_resolution_reference_kind";
alter table public."subject_resolution_attempts" add constraint "ck_subject_resolution_reference_kind" check (reference_kind IN ('organization_name', 'email_sender', 'email_domain', 'person_name', 'person_email', 'source_identifier', 'activity_identifier', 'document_identifier'));
alter table public."subject_resolution_attempts" drop constraint "ck_subject_resolution_state";
alter table public."subject_resolution_attempts" add constraint "ck_subject_resolution_state" check (state IN ('resolved', 'unresolved', 'conflict', 'stale', 'actor_boundary'));
alter table public."subject_resolution_attempts" drop constraint "ck_subject_resolution_usage";
alter table public."subject_resolution_attempts" add constraint "ck_subject_resolution_usage" check (usage IN ('identity', 'statement_speaker', 'affected_subject'));
alter table public."coordination_summary_configurations" drop constraint "ck_summary_config_retention";
alter table public."coordination_summary_configurations" add constraint "ck_summary_config_retention" check (retention_policy IN ('retained_indefinitely', 'class_b_30_days'));
alter table public."token_layers" drop constraint "ck_token_layers_origin";
alter table public."token_layers" add constraint "ck_token_layers_origin" check (origin IN ('native', 'ocr'));
drop index public."uq_fact_decision_effective";
CREATE UNIQUE INDEX uq_fact_decision_effective ON public.fact_decisions USING btree (project_id, subject_key, fact_type) WHERE ((superseded_by IS NULL) AND (fact_type IN ('utility_id', 'external_org', 'external_org_contact', 'utility_type', 'utility_subtype', 'utility_function', 'operational_status', 'size', 'material', 'oh_ug', 'row_placement', 'orientation', 'baseline', 'station_from', 'station_to', 'offset_from', 'offset_to', 'sue_level', 'conflict_description', 'resolution_strategy', 'notes', 'alignment', 'location_start', 'location_end', 'offset_side', 'potential_conflict', 'data_source', 'marked_resolution', 'committed_date', 'action_due_date', 'need_date', 'closure_result')));
